### ISSUE TITLE
Создание раздела "Карта подарков"

### ISSUE THREAD

**Issue by Alexa-alex** [mamont77/giftlink#22]
Создание нового раздела. Придумаю - напишу чётко задачи. Суть в том, что из каждой поездки мы везем подарочки и подарки. Какие? Долой магнитики)) пишу пока я сама, что интересного везу. Предлагаю людям добавить свои идеи. Через модерацию

**Comment by Alexa-alex** [comment]
Руслан, привет! надо добавить слово "руб" к цифрам. как у нас в идеях

**Comment by mamont77** [comment]
Готово.
