### ISSUE TITLE
Дата создания материала и ссылка на раздел

### ISSUE THREAD

**Issue by mamont77** [mamont77/giftlink#57]
Высылаю примерный вариант, как будет выглядеть в анонсе, то есть на главной странице и на общей странице раздела. В самой статье предлагаю размещать сразу под названием.
![vneshniy vid anonsa](https://cloud.githubusercontent.com/assets/970967/7648103/4ea83970-fae7-11e4-9da7-5fb678e1f058.jpg)
Смотри, там есть дата и название раздела (в данном случае - "искусство").

>>Страница разделав это имеешь ввиду это? http://giftlink.ru/creativity-kinds/knitting

Про разделы - да

>>По поводу даты, друпал вставляет дату автоматически. Но ты можешь ее менять вручную. А вот показывает он даты по типу контента, т.е. ты не можешь в одной статье показать дату, в другой спрятать. Это работает глобально для каждого типа контента. Можем сделать костыль: добавить дополнительную галочку "показывать дату".

По поводу даты - пусть будет всюду, кроме идей и товаров

Это задание выполнить после #58 и #59.

**Comment by mamont77** [comment]
Саша, в данный момент я добавил дату ТОЛЬКО в Мастер Классы. Посмотри как выглядит на рисунке ниже.

>> По поводу даты - пусть будет всюду, кроме идей и товаров

Я думаю в Сувенирах дата тоже ни к чему.

А вот по поводу категорий, во первых это отдельны функционал, который не зависит от даты, во вторых я не понимаю зачем добавлять категорию на страницу разделов. Смотри мой рисунок, будет очень мало масляное.
![- - 05-15-2015 13 02 29](https://cloud.githubusercontent.com/assets/970967/7650839/114ecd3e-fb03-11e4-853d-c231748a37b7.png)

В Радостях жизни, Находках, Сувенирах и тд. - категорий не существует. Соответвенно я не могу поставить категорию возле даты. Или ты хочешь создать новые категории? В таком случа желательно название категории, список терминов, и список типов материала где эти категории будут использоваться.

>> Страница разделав это имеешь ввиду это? http://giftlink.ru/creativity-kinds/knitting
>> Да. 

Возможно все таки ты имеешь виду эти страницы под страницами разделов?
http://giftlink.ru/gift-ideas
http://giftlink.ru/master-classes
Эта страница http://giftlink.ru/creativity-kinds/knitting - пусть будет называтся страницей категории ведь она отображает все материалы данной категории.

Из этого следует:
http://giftlink.ru/gift-ideas - здесь я могу добавить только дату, категории не созданы.
http://giftlink.ru/master-classes - здесь я могу добавить дату и категорию из словаря "Творчество". Если я добавлю термин из словаря "Сложность" будет много букффф.

Что ты думаешь об этом?

**Comment by Alexa-alex** [comment]
сейчас разберёмся. итак, разделы:
1) радости жизни
2) находки
3) интервью
4) мастер-классы

каждой статье из этих разделов соответствует только одно наименование из списка выше. то есть в мастер-классах, независимо от сложности или типа МК, каждая статья будет помечена словом "мастер-класс". это слово - ссылка на общую страницу со всеми мастер-классами.

сейчас проиллюстрирую, как это должно выглядеть на главной странице:
![image](https://cloud.githubusercontent.com/assets/9421454/7651653/8317724c-fb0b-11e4-93d2-55c794aad170.png)

сначала название раздела и дата. потом - название статьи. оформление не такое, конечно. дату - без года и цвета бледно серого. название категории - в цвет логотипа примерно и тоненькую рамку. название категории - заглавными буквами всё слово. 

вот как будет выглядеть в мастер-классах:
![image](https://cloud.githubusercontent.com/assets/9421454/7651704/0975dfae-fb0c-11e4-9db3-0940cd0353c4.png)

каждая такая иконка с названием - это ссылка- переход в один из четырех разделов. также в эти разделы можно попасть, нажав на одну ссылку верхней навигации на главной странице.

понятно объяснила? :)

**Comment by Alexa-alex** [comment]
у меня попутно возник вопрос. а новый материал из раздела мастер-класс я могу отображать в общем потоке статей на главной странице?

**Comment by mamont77** [comment]
>> понятно объяснила? :) 

Лучше не бывает )) Только ты разделы и категории путаешь. но я понял:))

>> новый материал из раздела мастер-класс я могу отображать в общем потоке статей на главной странице?

Почему бы и нет. Сделаем.

**Comment by mamont77** [comment]
Саша, необходима твоя консультация.
На главной страницу сделал, смотрится хорошо, что касается остальных разделов не очень как то...

Посмотри скрины. Масло масляное получилось.
![1](https://cloud.githubusercontent.com/assets/970967/7669327/b671c590-fc76-11e4-98d2-2c3847c9139a.png)
![2](https://cloud.githubusercontent.com/assets/970967/7669328/b675177c-fc76-11e4-9472-ad3484b756f0.png)
![3](https://cloud.githubusercontent.com/assets/970967/7669329/b678fc7a-fc76-11e4-9056-707739b33a01.png)
![4](https://cloud.githubusercontent.com/assets/970967/7669330/b6fb5cc4-fc76-11e4-87cb-716342753052.png)

Еще меня правый блок интересует. Там тоже раздел и дату выводить? С датой понятно, ап вот с разделом, сомневаюсь))
![gif 05-17-2015 09 23 38](https://cloud.githubusercontent.com/assets/970967/7669339/3eb3aa68-fc77-11e4-8aa3-dbb087189fa4.png)

Честно говоря, я бы оставил везде дату, но убрал бы названия разделов. Названия разделов акуальны только на главной странице.

Но решение за тобой.

**Comment by mamont77** [comment]
Обновил http://dev.giftlink.ru/ что бы ты могла посмотреть.

**Comment by Alexa-alex** [comment]
согласна. наименование раздела можно оставить только на главной странице. можно в таком случае выделять жирным название раздела в верхней навигации, в котором пользователь в данный момент находится?

в правом блоке и дата тоже не нужна. что касается названия правого блока - давай его вообще уберём? вот это "почитать о радостях" итд
в идеях (марафоне) раздела вообще нет)) и на главной странице, если отображается название, "идея", надо убрать. марафон у нас идёт там отдельной строкой и вообще несколько в стороне от остального контента.
ещё надо не забыть в верхнюю навигацию вставить "интервью". то есть такая последовательность: находки - радости жизни - интервью - мастер классы - марафон идей

**Comment by Alexa-alex** [comment]
и еще, мне как-то не по душе эта красная рамка)) давай поэкспериментируем)) например, в цвет заголовка??

**Comment by mamont77** [comment]
>> наименование раздела можно оставить только на главной странице. можно в таком случае выделять жирным название раздела в верхней навигации, в котором пользователь в данный момент находится?

готово

>> в правом блоке и дата тоже не нужна. что касается названия правого блока - давай его вообще уберём? вот это "почитать о радостях" итд

готово 

>>  и на главной странице, если отображается название, "идея", надо убрать. марафон у нас идёт там отдельной строкой и вообще несколько в стороне от остального контента.

Если я правильно тебя понял, этот баг описан в #65.

>> ещё надо не забыть в верхнюю навигацию вставить "интервью". то есть такая последовательность: находки - радости жизни - интервью - мастер классы - марафон идей

Вынес в отдельную задачу #67.

>> еще, мне как-то не по душе эта красная рамка)) давай поэкспериментируем)) например, в цвет заголовка??

готово

**Comment by Alexa-alex** [comment]
"""и на главной странице, если отображается название, "идея", надо убрать. марафон у нас идёт там отдельной строкой и вообще несколько в стороне от остального контента."""

я имела в виду вот эти наименования каждой идеи - выделено черным. совсем не нужно в марафоне. там не статьи, разделов нет. одни идеи) то же самое с товарами

![image](https://cloud.githubusercontent.com/assets/9421454/7679741/6459ec0e-fd68-11e4-8a8e-7dbc79a7fd8f.png)

**Comment by Alexa-alex** [comment]
1) у нас сейчас дата в разделе "марафон идей" есть у каждой идеи. она не нужна. и в товарах тоже.
2) размер даты у мастер-классов вырвался вперёд) надо бы уменьшить)

**Comment by mamont77** [comment]
Готово.
