### ISSUE TITLE
создать тип контента "находки"

### ISSUE THREAD

**Issue by mamont77** [mamont77/giftlink#59]
создаем новый тип контента "находки", делаем для находок дизайн отдельных страниц, блоков по образу и подобию как в "радости жизни".

**Comment by mamont77** [comment]
Саша, здесь http://dev.giftlink.ru/ на главной

**Comment by Alexa-alex** [comment]
убирай) у нас всё одним потоком пойдет. по мере появления нового материала (интервью или мастер-класса или находок каких) - они должны поочередно с датой отображаться на главной странице
