### ISSUE TITLE
Перенос существующего материала в другой тип контента

### ISSUE THREAD

**Issue by mamont77** [mamont77/giftlink#60]
>>Но мне бы хотелось уже часть из существующих статей перебросить в эти самые находки.

Саша, могу потратить время и установить это https://www.drupal.org/project/node_convert. Этот модуль позволяет изменить тип материала для суцщеествующей ноды. Или перенесешь вручную, создав новый материал и удалив старый. 
Какой пусть для тебя предпочтительнее?

**Comment by Alexa-alex** [comment]
сделаю вручную

**Comment by mamont77** [comment]
Отныне в каждом материале есть вот такая кнопка
![convert](https://cloud.githubusercontent.com/assets/970967/7770975/693e0fde-009c-11e5-97b8-951e99a1a4c2.png)
Дальше предложет выбрать тип материала, и затем попытается определить какие поля куда конвертировать. Если не сможет определить, спросит у тебя.
Надеюсь разберешься)))
