### ISSUE TITLE
Обновление системы безопасности

### ISSUE THREAD

**Issue by mamont77** [mamont77/giftlink#61]
Саша, посмотри все что красное здесь http://giftlink.ru/admin/reports/updates. Это не обязательно, но крайне желательно сделать. Иногда в друпале и модулях находят всякие дыры в безорпасности и модули обновляются. Обновление ядра и модулей займет чуть меньше одного часа.
Делать или оставить?

**Comment by Alexa-alex** [comment]
я плачУ за этот час?

**Comment by mamont77** [comment]
Саша, это ведь тоже работа) Конечно ты платишь. Это делать на само деле не обязательно. Случаев что бы взломали drupal сайт довольно мало. Если бы это был корпоративный сайт, я бы обновил тебе все даже не спрашивая, так как это потенциальная угроза компании. Но этот сайт твое хобби, и врядли будет интересен в плане взломать кому либо. Я увидел и обязан написать, ты принимаешь решение )))

**Comment by Alexa-alex** [comment]
ну это я к тому, что может там один раз нажать кнопку - "обновить" и кури себе дальше бамбук))

**Comment by Alexa-alex** [comment]
давай пока отложим))

**Comment by mamont77** [comment]
>> ну это я к тому, что может там один раз нажать кнопку - "обновить" и кури себе дальше бамбук))

Да. но есть нюансы. Автор модуля мог добавить не нужный нам новый функционал или удалить старый, который мы используем. Поэтому надо проверять новый код, и тесрировать функционал сайта.

Пока зыкрываю задачу.
