### ISSUE TITLE
на главной странице убрать наименование "идеи подарков", которая стоит над статьями

### ISSUE THREAD

**Issue by mamont77** [mamont77/giftlink#62]

**Comment by mamont77** [comment]
Саша, я это название переименовал в "РАДОСТИ ЖИЗНИ". Убрать вообще?
![1](https://cloud.githubusercontent.com/assets/970967/7650303/ad089aee-fafd-11e4-850c-1d853aa0b7c9.png)

**Comment by Alexa-alex** [comment]
да

**Comment by mamont77** [comment]
Задача должна была стоять так.
Убрать заголовок блока "идеи подарков". В этом блоке выводить почти все новые материалы, а именно: "сувениры", "находки", "радости жизни".
