### ISSUE TITLE
Drupal bug: На нлавной странице по клику на "загрузить еще" грузятся материалы из марафона идей

### ISSUE THREAD

**Issue by mamont77** [mamont77/giftlink#65]
![0](https://cloud.githubusercontent.com/assets/970967/7669362/a09f35de-fc78-11e4-9765-444b438bb64e.png)

**Comment by mamont77** [comment]
Конечно самый ленивый вариант, убрать "показать еще" на главной. Очень странно, но друпал путает откуда брать материалы, когда стоит 2 похожих блока. Но если поковырятся - задача решаема. Не было достаочно времени иследовать этот баг.

**Comment by Alexa-alex** [comment]
давай тогда просто увеличим количество статей до штук 40. там сейчас меньше в целом. это сильно увеличит нагрузку на загрузку)) главной страницы?

**Comment by mamont77** [comment]
не сильно увеличит. попробуем во всяком случае.

**Comment by Alexa-alex** [comment]
ок

**Comment by mamont77** [comment]
Готово. Скоро выложу обновленную версию на DEV.
