### ISSUE TITLE
Внешний вид превью раздела "Сувениры" для главной страницы

### ISSUE THREAD

**Issue by Alexa-alex** [mamont77/giftlink#66]
по поводу превьюшки для раздела "сувениры". давай его сделаем таким же, как в интервью. если я не ошибаюсь, в интервью у нас 2 возможности - разместить вертикальное фото или в круге с цитатой. можно для сувениров сделать тоже такую двойную опцию, но так, чтобы можно было выбрать между вертикалью и горизонталью? + название города (в интервью - имя фамилия) + предложение (но без кавычек!!)

**Comment by mamont77** [comment]
Сделать можно как ты предложила.
Хочу лишь обратить внимание чта превьшка уже имеет уникальный свой собственный дизизайн.
![giftlink ru - google chrome 05-18-2015 08 59 56](https://cloud.githubusercontent.com/assets/970967/7675090/85a664ae-fd3c-11e4-8e26-d02a41a2f5b3.png)
Вдруг это тебе тоже нравится и не надо тратить время.

**Comment by Alexa-alex** [comment]
да, мне нравится такой внешний вид. оставляем!
