### ISSUE TITLE
Отдельная страница для раздела "интервью"

### ISSUE THREAD

**Issue by mamont77** [mamont77/giftlink#67]
>>ещё надо не забыть в верхнюю навигацию вставить "интервью". то есть такая последовательность: находки - радости жизни - интервью - мастер классы - марафон идей

У нас "интервью" идет в "Радости жизни". Пример страницы http://giftlink.ru/interview/lyudi-doveryayut-mne-chast-svoey-zhizni. Посмотри на хлебные крошки: Главная -> Радости жизни ->  Интервью -> Люди доверяют мне часть своей жизни.
Отдельной страницы http://giftlink.ru.dev/interview/ не существует. Я могу ее создать (views, необходимые блоки и подправить наследовательность в дизайне), но на это уйдет пару часов.

Вторая проблема, с которой мы долго боролись когда то. Кнопка подписаться на идеи выглядит сломаной на малых мониторах, после того как я добавил "находки". Если добавлю  "интервью", это сломает дизайн еще больше.

Как быть? Любые идеи.

Самывй дешевый способ, оставить эту кнопку только на главной странице, поставить над блоком "стань волшебником". 

Вариант немного дороже, убрать эту кнопку вообще. Сам попап (он появляется по нажатию на кнопке) показывать автоматически через 10 секунд просмотра страницы. В этом случае еслим пользователь нажмет закрыть, не показывать этот попап в течении недели или месяца вообще.
Возможно этот попап лучше облагородить вставив фоновую картинку как здесь http://vixi.com/ (ждать 10 сек).

**Comment by Alexa-alex** [comment]
1) интервью надо исправить... вынести в отдельный раздел
2) можно сделать выпадающий список? например, в верхнем меню "о подарках" и выпадает список - "радости жизни", "находки", "интервью", "мастер-классы". то есть верхнее меню на маленьких экранах - это "о подарках", "марафон идей".

**Comment by mamont77** [comment]
Меню можно сделать выпадающим. Но глобально, как и для больших, так и для маленьких экранов. В момент когда сервер генерирует код сайта для браузера, сервер еще не знает какой экран у пользователя. Соответвенно для выпадающего меню придется подправить дизайн навигации.

**Comment by Alexa-alex** [comment]
если глобально, то мне уже не очень))) давай перенесем кнопку "подписаться на идеи" и фэйсбук туда, где сейчас "стань волшебником". эта акция закончилась и неизвестно, когда повторится. вероятно, к след новому году.
дизайн пока не знаю, как сделать. пока скажи мне, такой вариант пойдет?

**Comment by mamont77** [comment]
Думаю пойдёт. Сегодня я не уверен что доберусь до компа, только телефон
имею. Максимум завтра сделаю. Кажется это был последний вопрос. Остальное
мелочи.
19 мая 2015 г. 14:39 пользователь "Alexa-alex" <notifications@github.com>
написал:

**Comment by mamont77** [comment]
Готово. Скоро обновлю DEV.
