### ISSUE TITLE
Сломанная навигация, потому что много пунктов меню

### ISSUE THREAD

**Issue by mamont77** [mamont77/giftlink#68]
Создаю эту задачу, потому что она не избежна.
Ты предложила выпадающий список. Скорее всего это самая дешевая и лучшая идея.
Возьмем ее как наиболее приоритетный путь.

Или как вариант мой набросок.
![odesk team room 05-19-2015 12 15 22](https://cloud.githubusercontent.com/assets/970967/7699508/0a47620a-fe21-11e4-9909-703896d18961.png)

**Comment by mamont77** [comment]
Я проверил. Меню можно сделать выпадающим. Это не долго.
Но это будет глобально для любых мониторов, как для 22 дюйма, так и для 16 дюйма.
Жду подтверждения.

**Comment by Alexa-alex** [comment]
сейчас подумаю. напишу

**Comment by mamont77** [comment]
Ты уже написала в соседней задаче.))) там где "стань волшебником".
19 мая 2015 г. 14:42 пользователь "Alexa-alex" <notifications@github.com>
написал:

**Comment by Alexa-alex** [comment]
да) решила ещё подумать)

**Comment by Alexa-alex** [comment]
внимательный, блин)

**Comment by Alexa-alex** [comment]
давай сделаем так.
верхняя строка - это только наименования разделов. надо там аккуратно сделать, симметрично, чтобы правая сторона не сильно "провисала", то есть без большого пробела. разделы идут так: находки - радости жизни - интервью - мастер-классы - сувениры (если помещается!!!) - марафон идей. ничего же не забыла?))
далее. поднимаем сувениры вверх на место волшебника. под ним идёт вот такой блок. примерный вид:
![image](https://cloud.githubusercontent.com/assets/9421454/7702528/6bd126d8-fe39-11e4-8de6-66313a80402b.png)

у нас будет так
                                         БЕСПЛАТНАЯ ДОСТАВКА 
                                                 идей подарков
                                          ----- кнопка подписки -----

                                   ---- кнопка фейсбука и инстаграмма ----

**Comment by mamont77** [comment]
Как тебе такой вариант?
![giftlink ru - mozilla firefox 05-20-2015 17 18 14](https://cloud.githubusercontent.com/assets/970967/7727869/5e65dd5a-ff14-11e4-83f9-97f261aba440.png)
Вроди бы готово.

**Comment by mamont77** [comment]
Готово.
Так выглядит на разных екранах.
![11](https://cloud.githubusercontent.com/assets/970967/7768497/53f1273c-0084-11e5-9bb1-1043080a0430.png)
![22](https://cloud.githubusercontent.com/assets/970967/7768499/53f7d71c-0084-11e5-931a-e88a62bd6ec7.png)
![33](https://cloud.githubusercontent.com/assets/970967/7768498/53f7f1c0-0084-11e5-95fb-1498dd0f7bd1.png)
![Uploading 44.png…]()
Сервер обновлю при первой возможности.
